# Generated by Django 5.1.4 on 2025-01-01 17:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='post/')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('authror', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_authror', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
