# Generated by Django 5.1.4 on 2025-01-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=50)),
                ('logo', models.TextField(max_length=30)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=500)),
                ('description', models.TextField(max_length=300)),
                ('fc_link', models.URLField()),
                ('x_link', models.URLField()),
                ('inst_link', models.URLField()),
                ('linkedin_link', models.URLField()),
            ],
        ),
    ]
