# Generated by Django 5.1.4 on 2025-01-01 20:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='cteated_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
