# Generated by Django 5.1.4 on 2025-01-01 20:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_property_cteated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='cteated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
