# Generated by Django 5.1.4 on 2025-01-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_alter_property_cteated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='category',
        ),
        migrations.RemoveField(
            model_name='property',
            name='price',
        ),
        migrations.AddField(
            model_name='property',
            name='num_bathroom',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='num_bed',
            field=models.IntegerField(default=1),
        ),
    ]
