# Generated by Django 5.1.4 on 2025-01-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_property_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertybook',
            name='children',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertybook',
            name='guest',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
