# Generated by Django 4.2.17 on 2025-01-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_propertybook_children_propertybook_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertybook',
            name='children',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=2),
        ),
        migrations.AlterField(
            model_name='propertybook',
            name='guest',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=2),
        ),
    ]
